import { BaiduLanguagePredict, BaiduTranslator } from "./source/baidu.js";
import { DeepL } from "./source/deepl.js";
import { GoogleTranslate, GoogleBrowserTranslate } from "./source/google.js";
import { MicrosoftTranslator, MicrosoftBrowserTranslator } from "./source/microsoft.js";
import { SogouBrowserTranslator } from "./source/sogou.js";
import { YandexDetect, YandexBrowserTranslator } from "./source/yandex.js";
import { IsChs, IsCht } from "./misc.js";
import { TranslatorFunction } from "types.js";
declare const Translator: TranslatorFunction;
export { Translator, BaiduLanguagePredict, YandexDetect, BaiduTranslator, DeepL, GoogleBrowserTranslate, GoogleTranslate, MicrosoftBrowserTranslator, MicrosoftTranslator, SogouBrowserTranslator, YandexBrowserTranslator, IsChs, IsCht };
