name: Build scripts

on:
    push:
        branches:
            - master
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"
                  cache-dependency-path: yarn.lock
            - name: yarn install and build
              run: |
                  yarn run rebuild
                  mkdir npm && mv dist LICENSE README.md package.json npm && mv npm/dist/esm/index.browser.d.ts npm/dist/esm/translator.mod.d.ts
            - name: Deploy
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: git@github.com:BANKA2017/translator-utils.git
                  BRANCH: npm
                  FOLDER: npm
                  COMMIT_NAME: ${{ secrets.COMMIT_NAME }}
                  COMMIT_EMAIL: ${{ secrets.COMMIT_EMAIL }}
                  SQUASH_HISTORY: true
                  MESSAGE: "npm: {msg} ~ {sha}"
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
